import React from 'react';

function Translator({ code, value, classNames }) {
  if (!code || !value || code==='EN'){ 
    //console.log("Error",code,value);
    return <span className={classNames}>{value}</span>; 
  }
  value = value.trim();
  const id = translationData.find(item => item.value === value)?.id;
  if (id){
    const translation = translationData.find(item => item.id === id && item.code === code);
    if (translation){
      return <span className={classNames}>{translation.value}</span>;
    }else{
      return <span className={classNames}>{translateAllWords(code, value)}</span>;
    }
  } else {
    return <span className={classNames}>{translateAllWords(code, value)}</span>;
  }
}

function translateAllWords(code, value) {
  var wordsArray = value.split(" ");
  var translatedWordsArray = [];
  for (var i = 0; i < wordsArray.length; i++){
    const id = translationData.find(item => item.value === wordsArray[i])?.id;
    if (id){
      const translation = translationData.find(item => item.id === id && item.code === code);
      translatedWordsArray.push(translation ? translation.value : wordsArray[i]);
    }else{
      translatedWordsArray.push(wordsArray[i]);
    }
  }
  return translatedWordsArray.join(" ");
}

export default Translator;

const translationData = [
  { id:1, code: `EN`, value: `Account` },
  { id:2, code: `EN`, value: `Sign In` },
  { id:3, code: `EN`, value: `Welcome to Reserwave` },
  { id:4, code: `EN`, value: `Your journey to discovering, reserving, and enjoying experiences starts here.` },
  { id:5, code: `EN`, value: `Sign Up` },
  { id:6, code: `EN`, value: `Submit` },
  { id:7, code: `EN`, value: `Password` },
  { id:8, code: `EN`, value: `First Name` },
  { id:9, code: `EN`, value: `Last Name` },
  { id:10, code: `EN`, value: `Phone` },
  { id:11, code: `EN`, value: `Reservations` },
  { id:12, code: `EN`, value: `Store Reservations` },
  { id:13, code: `EN`, value: `Search services` },
  { id:14, code: `EN`, value: `Region, Town, City` },
  { id:15, code: `EN`, value: `Stores near` },
  { id:16, code: `EN`, value: `your location` },
  { id:17, code: `EN`, value: `Copyright © 2023 Reserwave - All rights reserved` },
  { id:18, code: `EN`, value: `Terms & Conditions` },
  { id:19, code: `EN`, value: `Privacy Policy` },
  { id:20, code: `EN`, value: `Become a Partner` },
  { id:21, code: `EN`, value: `Choose a service` },
  { id:22, code: `EN`, value: `Pick a date` },
  { id:23, code: `EN`, value: `Select a time` },
  { id:24, code: `EN`, value: `Book it` },
  { id:25, code: `EN`, value: `Reviews` },
  { id:26, code: `EN`, value: `Oops! It appears that there are currently no reviews for this store.` },
  { id:27, code: `EN`, value: `We're sorry, but it seems that this store is not currently offering any services.` },
  { id:28, code: `EN`, value: `Good news! You don't have any active reservations at the moment. Book a new service to get started on your next experience.` },
  { id:29, code: `EN`, value: `Oops! It looks like there are currently no stores in the selected location. Try adjusting your location or explore nearby areas for available options.` },
  { id:30, code: `EN`, value: `January` },
  { id:31, code: `EN`, value: `February` },
  { id:32, code: `EN`, value: `March` },
  { id:33, code: `EN`, value: `April` },
  { id:34, code: `EN`, value: `May` },
  { id:35, code: `EN`, value: `June` },
  { id:36, code: `EN`, value: `July` },
  { id:37, code: `EN`, value: `August` },
  { id:38, code: `EN`, value: `September` },
  { id:39, code: `EN`, value: `October` },
  { id:40, code: `EN`, value: `November` },
  { id:41, code: `EN`, value: `December` },
  { id:42, code: `EN`, value: `Mon` },
  { id:43, code: `EN`, value: `Tus` },
  { id:44, code: `EN`, value: `Wed` },
  { id:45, code: `EN`, value: `Thu` },
  { id:46, code: `EN`, value: `Fri` },
  { id:47, code: `EN`, value: `Sat` },
  { id:48, code: `EN`, value: `Sun` },
  { id:49, code: `EN`, value: `Sign Out` },
  { id:50, code: `EN`, value: `Cancel` },
  { id:51, code: `EN`, value: `Currently, there are no reservations to display. Check back later for updates.` },
  { id:52, code: `EN`, value: `Effective Date` },
  { id:53, code: `EN`, value: `Closed` },
  { id:54, code: `EN`, value: `Opens at` },
  { id:55, code: `EN`, value: `guests` },
  { id:56, code: `EN`, value: `Votes` },
  { id:57, code: `EN`, value: `Calendar` },
  { id:58, code: `EN`, value: `Favourites` },
  { id:59, code: `EN`, value: `Settings` },
  { id:60, code: `EN`, value: `Account Settings` },
  { id:61, code: `EN`, value: `Full Name` },
  { id:62, code: `EN`, value: `Subscription Status` },
  { id:63, code: `EN`, value: `Manage Your Subscription` },
  { id:64, code: `EN`, value: `Exciting things are happening behind the scenes! This area is temporarily unavailable as we're working hard to bring you new features. Stay tuned!` },
  { id:65, code: `EN`, value: `Welcome to Reserwave! These terms and conditions ("Terms") constitute a legally binding agreement between you and Reserwave. Please read these Terms carefully before using our platform. By accessing or using Reserwave, you agree to comply with and be bound by these Terms. If you do not agree with any part of these Terms, please refrain from using our platform.` },
  { id:66, code: `EN`, value: `By using Reserwave, you agree to these Terms and any updates or modifications that may occur. Your continued use of the platform after such modifications constitutes your acceptance of the revised Terms.` },
  { id:67, code: `EN`, value: `Description of Services` },
  { id:68, code: `EN`, value: `Reserwave provides a comprehensive platform for users to discover and make reservations at nearby stores across various niches. Our goal is to enhance your experience by connecting you with a diverse range of businesses, making it easier for you to explore and patronize local establishments.` },
  { id:69, code: `EN`, value: `User Data Privacy` },
  { id:70, code: `EN`, value: `At Reserwave, we take the privacy and security of your data seriously. Any information collected from users is securely stored and is not made public or sold to third parties. Please refer to our` },
  { id:71, code: `EN`, value: `Privacy Policy` },
  { id:72, code: `EN`, value: `for a detailed overview of how we collect, use, and protect your data.` },
  { id:73, code: `EN`, value: `Store Information Confidentiality` },
  { id:74, code: `EN`, value: `We want to assure our partner stores that we prioritize the confidentiality of their information. Reserwave does not disclose any details about store revenue, reservation statistics, or any other proprietary data belonging to the stores on our platform.` },
  { id:75, code: `EN`, value: `User Eligibility` },
  { id:76, code: `EN`, value: `You must be eligible to use Reserwave. By using our platform, you confirm that you meet any age or other eligibility requirements.` },
  { id:77, code: `EN`, value: `User Conduct` },
  { id:78, code: `EN`, value: `Users must adhere to acceptable behavior on Reserwave. Any misuse or violation of these terms may result in the termination of your account. We encourage a respectful and positive community for all users.` },
  { id:79, code: `EN`, value: `Termination of Accounts` },
  { id:80, code: `EN`, value: `We reserve the right to terminate user accounts or services under conditions deemed appropriate by Reserwave. This includes cases of non-compliance with these Terms or any inappropriate behavior on the platform.` },
  { id:81, code: `EN`, value: `Limitation of Liability` },
  { id:82, code: `EN`, value: `Reserwave is not liable for any damages incurred by users or stores. Users and stores use our platform at their own risk. We strive to provide a reliable and secure platform, but we cannot guarantee uninterrupted, error-free, or secure access to our services.` },
  { id:83, code: `EN`, value: `Changes to Terms` },
  { id:84, code: `EN`, value: `We may update or modify these Terms, and users will be informed of such changes through notifications on the platform or via email. Continued use of Reserwave constitutes acceptance of the updated Terms.` },
  { id:85, code: `EN`, value: `Contact Information` },
  { id:86, code: `EN`, value: `For questions or concerns, please contact us at` },
  { id:87, code: `EN`, value: `We value your feedback and are here to assist you.` },
  { id:88, code: `EN`, value: `Entire Agreement` },
  { id:89, code: `EN`, value: `These Terms constitute the entire agreement between users and Reserwave, superseding any prior agreements, discussions, or understandings.` },
  { id:90, code: `EN`, value: `Severability` },
  { id:91, code: `EN`, value: `If any part of these Terms is found to be unenforceable, the remainder of the Terms will remain in effect.` },
  { id:92, code: `EN`, value: `Information We Collect` },
  { id:93, code: `EN`, value: `User Provided Information` },
  { id:94, code: `EN`, value: `We may collect personal information that you voluntarily provide when using Reserwave. This may include, but is not limited to:` },
  { id:95, code: `EN`, value: `Name` },
  { id:96, code: `EN`, value: `Email address` },
  { id:97, code: `EN`, value: `Phone number` },
  { id:98, code: `EN`, value: `User preferences` },
  { id:99, code: `EN`, value: `Automatically Collected Information` },
  { id:100, code: `EN`, value: `We may also collect information automatically as you navigate and interact with Reserwave. This may include:` },
  { id:101, code: `EN`, value: `Device information` },
  { id:102, code: `EN`, value: `IP address` },
  { id:103, code: `EN`, value: `Usage data` },
  { id:104, code: `EN`, value: `Location data` },
  { id:105, code: `EN`, value: `How We Use Your Information` },
  { id:106, code: `EN`, value: `We use the collected information for the following purposes:` },
  { id:107, code: `EN`, value: `To provide and improve our services` },
  { id:108, code: `EN`, value: `To personalize your experience on Reserwave` },
  { id:109, code: `EN`, value: `To communicate with you, including responding to inquiries` },
  { id:110, code: `EN`, value: `To send relevant notifications and updates` },
  { id:111, code: `EN`, value: `To analyze and enhance the security of our platform` },
  { id:112, code: `EN`, value: `Data Security` },
  { id:113, code: `EN`, value: `We take the security of your information seriously and implement reasonable security measures to protect it from unauthorized access, disclosure, alteration, and destruction.` },
  { id:114, code: `EN`, value: `Sharing of Information` },
  { id:115, code: `EN`, value: `We do not sell or share your personal information with third parties for their marketing purposes. We may share your information with third-party service providers who assist us in operating our platform, provided they agree to keep this information confidential.` },
  { id:116, code: `EN`, value: `Cookies and Tracking Technologies` },
  { id:117, code: `EN`, value: `Reserwave uses cookies and similar tracking technologies to enhance your experience on our platform. You can manage your cookie preferences through your browser settings.` },
  { id:118, code: `EN`, value: `Your Choices` },
  { id:119, code: `EN`, value: `You have the right to` },
  { id:120, code: `EN`, value: `Access, update, or delete your personal information` },
  { id:121, code: `EN`, value: `Opt-out of certain communications` },
  { id:122, code: `EN`, value: `Disable cookies through your browser settings` },
  { id:123, code: `EN`, value: `Changes to this Privacy Policy` },
  { id:124, code: `EN`, value: `We may update this Privacy Policy to reflect changes in our data practices. The effective date will be revised accordingly, and we encourage you to review this page periodically for any updates.` },
  { id:125, code: `EN`, value: `Contact Us` },
  { id:126, code: `EN`, value: `If you have any questions or concerns regarding this Privacy Policy, please contact us at` },
  { id:127, code: `EN`, value: `Connect with Customers, Manage Reservations` },
  { id:128, code: `EN`, value: `Welcome to Reserwave, where we connect local businesses with customers like never before. Join us and grow your business by becoming a partner.` },
  { id:129, code: `EN`, value: `Key Benefits` },
  { id:130, code: `EN`, value: `Increase Visibility: Reach a broader audience in your local community.` },
  { id:131, code: `EN`, value: `Seamless Reservations: Effortlessly manage reservations through our user-friendly platform.` },
  { id:132, code: `EN`, value: `Boost Your Customer Base: Attract new customers looking for businesses like yours.` },
  { id:133, code: `EN`, value: `How It Works` },
  { id:134, code: `EN`, value: `Sign Up: Fill out a simple form with your business details to get started.` },
  { id:135, code: `EN`, value: `Add Your Services: Incorporate your services with the flexibility to create your own bundles.` },
  { id:136, code: `EN`, value: `Start Connecting: Once approved, start receiving reservations and engaging with new customers.` },
  { id:137, code: `EN`, value: `Need Presentation?` },
  { id:138, code: `EN`, value: `Fullfill the form down below` },
  { id:139, code: `EN`, value: `Request Presentation` },
  { id:140, code: `EN`, value: `Join the subscription` },
  { id:141, code: `EN`, value: `If you want to join our plaform, you can start your subscription now. Then our team will contact you soon to submit your store on Reserwave.` },
  { id:142, code: `EN`, value: `Contact Us Now` },
  { id:143, code: `EN`, value: `For any inquiries or assistance, our support team is ready to help. Please contact us at` },
  { id:144, code: `EN`, value: `Soon: Interactive Map` },
  { id:145, code: `EN`, value: `Selceted Service` },
  { id:146, code: `EN`, value: `Your Location` },
  { id:147, code: `EN`, value: `Inactive` },
  { id:148, code: `EN`, value: `Active` },
  { id:149, code: `EN`, value: `Open` },
  { id:150, code: `EN`, value: `Until` },
  { id:151, code: `EN`, value: `Accepted at` },
  { id:152, code: `EN`, value: `Combine it with` },
  { id:153, code: `EN`, value: `Not accepted yet` },
  { id:154, code: `EN`, value: `Cancelled` },
  { id:155, code: `EN`, value: `Accept` },
  { id:156, code: `EN`, value: `at` },
  { id:157, code: `EN`, value: `Users` },
  { id:158, code: `EN`, value: `Services` },
  { id:159, code: `EN`, value: `Stores` },
  { id:160, code: `EN`, value: `Subcategories` },
  { id:161, code: `EN`, value: `Categories` },
  { id:162, code: `EN`, value: `Buy Subscription Now` },
  { id:163, code: `EN`, value: `Acceptance of Terms` },
  { id:164, code: `EN`, value: `Welcome to Reserwave! This Privacy Policy outlines how Reserwave ("we," "us," or "our") collects, uses, and protects your personal information when you use our platform. By accessing or using Reserwave, you agree to the terms outlined in this Privacy Policy.` },
  { id:165, code: `EN`, value: `Opens` },
  { id:166, code: `EN`, value: `Monday` },
  { id:167, code: `EN`, value: `Tuesday` },
  { id:168, code: `EN`, value: `Wednesday` },
  { id:169, code: `EN`, value: `Thursday` },
  { id:170, code: `EN`, value: `Friday` },
  { id:171, code: `EN`, value: `Saturday` },
  { id:172, code: `EN`, value: `Sunday` },
  { id:173, code: `EN`, value: `monday` },
  { id:174, code: `EN`, value: `tuesday` },
  { id:175, code: `EN`, value: `wednesday` },
  { id:176, code: `EN`, value: `thursday` },
  { id:177, code: `EN`, value: `friday` },
  { id:178, code: `EN`, value: `saturday` },
  { id:179, code: `EN`, value: `sunday` },
  { id:180, code: `EN`, value: `Please select a service before proceeding` },
  { id:181, code: `EN`, value: `Please add a date before proceeding` },
  { id:182, code: `EN`, value: `Please choose a time before proceeding` },
  { id:183, code: `EN`, value: `Login required to proceed` },
  { id:184, code: `EN`, value: `Success` },
  { id:185, code: `EN`, value: `Another reservation is already scheduled for this time under this account` },
  { id:186, code: `EN`, value: `Oops! Something didn't go as planned` },
  { id:187, code: `EN`, value: `Please enter your email to log in` },
  { id:188, code: `EN`, value: `The email entered is not valid` },
  { id:189, code: `EN`, value: `To proceed, enter your password` },
  { id:190, code: `EN`, value: `Email cannot be empty` },
  { id:191, code: `EN`, value: `Please enter your name to proceed` },
  { id:192, code: `EN`, value: `Will be in touch shortly` },
  { id:193, code: `EN`, value: `Please provide your first name` },
  { id:194, code: `EN`, value: `Please provide your last name` },
  { id:195, code: `EN`, value: `Please enter your email` },
  { id:196, code: `EN`, value: `Please enter your phone number` },
  { id:197, code: `EN`, value: `Please enter a valid phone number` },
  { id:198, code: `EN`, value: `Please enter a password` },
  { id:199, code: `EN`, value: `Password must be at least 8 characters long` },
  { id:200, code: `EN`, value: `Greetings! You're now part of Reserwave` },
  { id:201, code: `EN`, value: `Reservation Cancellation Confirmed` },
  { id:202, code: `EN`, value: `Logged Out` },
  { id:203, code: `EN`, value: `Double-check your decision` },
  { id:204, code: `EN`, value: `This reservation will be permanently removed and cannot be restored` },
  { id:205, code: `EN`, value: `remaining` },
  { id:206, code: `EN`, value: `available` },
  { id:207, code: `EN`, value: `You don't have any favourite stores στις the moment. For easier access later, include a store on this list.` },
  { id:208, code: `EN`, value: `Explore Now` },
  { id:209, code: `EN`, value: `Slug` },
  { id:210, code: `EN`, value: `Category` },
  { id:211, code: `EN`, value: `Area` },
  { id:212, code: `EN`, value: `Street` },
  { id:213, code: `EN`, value: `City` },
  { id:214, code: `EN`, value: `Zip Code` },
  { id:215, code: `EN`, value: `Country` },
  { id:216, code: `EN`, value: `Concurrent` },
  { id:217, code: `EN`, value: `Image Url` },
  { id:218, code: `EN`, value: `Visibility` },
  { id:219, code: `EN`, value: `Store Settings` },
  { id:220, code: `EN`, value: `Title` },
  { id:221, code: `EN`, value: `Description` },
  { id:222, code: `EN`, value: `Duration` },
  { id:223, code: `EN`, value: `Price` },
  { id:224, code: `EN`, value: `List Price` },
  { id:225, code: `EN`, value: `Independent` },
  { id:226, code: `EN`, value: `Auto Accept` },
  { id:227, code: `EN`, value: `Can Combine` },
  { id:228, code: `EN`, value: `Can Not Combine` },
  { id:229, code: `EN`, value: `Yes` },
  { id:230, code: `EN`, value: `No` },
  { id:231, code: `EN`, value: `Add new` },
  { id:232, code: `EN`, value: `Save` },
  { id:233, code: `EN`, value: `Working Hours` },
  { id:234, code: `EN`, value: `Day` },
  { id:235, code: `EN`, value: `Start time` },
  { id:236, code: `EN`, value: `End time` },
  { id:237, code: `EN`, value: `Back to Homepage` },
  { id:238, code: `EN`, value: `Explore` },
  { id:239, code: `EN`, value: `Sign in` },
  { id:240, code: `EN`, value: `Partner` },
  { id:241, code: `EN`, value: `Forgot my password` },
  { id:242, code: `EN`, value: `Continue with Google` },
  { id:243, code: `EN`, value: `Account Recovery` },
  { id:244, code: `EN`, value: `Under review` },
  { id:245, code: `EN`, value: `There aren't any` },
  { id:246, code: `EN`, value: `on Reserwave near` },
  { id:247, code: `EN`, value: `yet.` },
  { id:248, code: `EN`, value: `It's not you, it's us! We're working hard to expand and hope to come to your area soon.` },
  { id:249, code: `EN`, value: `We're sorry, but it seems that this store is not currently offering any services.` },
  { id:250, code: `EN`, value: `To proceed with your booking, create a free account.` },
  { id:1, code: `EL`, value: `Λογαριασμός` },
  { id:2, code: `EL`, value: `Σύνδεση` },
  { id:3, code: `EL`, value: `Καλώς ήλθατε στο Reserwave` },
  { id:4, code: `EL`, value: `Το ταξίδι σας για να ανακαλύψετε, να κλείσετε και να απολαύσετε εμπειρίες ξεκινά εδώ.` },
  { id:5, code: `EL`, value: `Εγγραφή` },
  { id:6, code: `EL`, value: `Ολοκλήρωση` },
  { id:7, code: `EL`, value: `Κωδικός` },
  { id:8, code: `EL`, value: `Όνομα` },
  { id:9, code: `EL`, value: `Επίθετο` },
  { id:10, code: `EL`, value: `Κινητό` },
  { id:11, code: `EL`, value: `Κρατήσεις` },
  { id:12, code: `EL`, value: `Κρατήσεις καταστήματος` },
  { id:13, code: `EL`, value: `Αναζήτηση υπηρεσιών` },
  { id:14, code: `EL`, value: `Περιοχή, πόλη` },
  { id:15, code: `EL`, value: `Καταστήματα κοντά στη περιοχή` },
  { id:16, code: `EL`, value: `σας` },
  { id:17, code: `EL`, value: `Πνευματικά δικαιώματα © 2023 Reserwave` },
  { id:18, code: `EL`, value: `Όροι & Προϋποθέσεις` },
  { id:19, code: `EL`, value: `Πολιτική Απορρήτου` },
  { id:20, code: `EL`, value: `Γίνε συνέταιρος` },
  { id:21, code: `EL`, value: `Επιλέξτε μια υπηρεσία` },
  { id:22, code: `EL`, value: `Διαλέξτε μια ημερομηνία` },
  { id:23, code: `EL`, value: `Επιλέξτε μια ώρα` },
  { id:24, code: `EL`, value: `Ολοκλήρωση` },
  { id:25, code: `EL`, value: `Κριτικές` },
  { id:26, code: `EL`, value: `Ωχ! Φαίνεται ότι αυτή τη στιγμή δεν υπάρχουν κριτικές για αυτό το κατάστημα.` },
  { id:27, code: `EL`, value: `Λυπούμαστε, αλλά φαίνεται ότι αυτό το κατάστημα δεν προσφέρει καμία υπηρεσία αυτήν τη στιγμή.` },
  { id:28, code: `EL`, value: `Καλα νέα! Δεν έχετε ενεργές κρατήσεις αυτήν τη στιγμή. Κάντε κράτηση για μια νέα υπηρεσία για να ξεκινήσετε την επόμενη εμπειρία σας.` },
  { id:29, code: `EL`, value: `Ωχ! Φαίνεται ότι αυτή τη στιγμή δεν υπάρχουν καταστήματα στην επιλεγμένη τοποθεσία. Δοκιμάστε να προσαρμόσετε την τοποθεσία σας ή εξερευνήστε κοντινές περιοχές για διαθέσιμες επιλογές.` },
  { id:30, code: `EL`, value: `Ιανουάριος` },
  { id:31, code: `EL`, value: `Φεβρουάριος` },
  { id:32, code: `EL`, value: `Μάρτιος` },
  { id:33, code: `EL`, value: `Απρίλιος` },
  { id:34, code: `EL`, value: `Μάϊος` },
  { id:35, code: `EL`, value: `Ιούνιος` },
  { id:36, code: `EL`, value: `Ιούλιος` },
  { id:37, code: `EL`, value: `Αύγουστος` },
  { id:38, code: `EL`, value: `Σεπτέμβριος` },
  { id:39, code: `EL`, value: `Οκτώβριος` },
  { id:40, code: `EL`, value: `Νοέμβριος` },
  { id:41, code: `EL`, value: `Δεκέμβριος` },
  { id:42, code: `EL`, value: `Δευ` },
  { id:43, code: `EL`, value: `Τρι` },
  { id:44, code: `EL`, value: `Τετ` },
  { id:45, code: `EL`, value: `Πεμ` },
  { id:46, code: `EL`, value: `Παρ` },
  { id:47, code: `EL`, value: `Σαβ` },
  { id:48, code: `EL`, value: `Κυρ` },
  { id:49, code: `EL`, value: `Αποσύνδεση` },
  { id:50, code: `EL`, value: `Ακύρωση` },
  { id:51, code: `EL`, value: `Προς το παρόν, δεν υπάρχουν κρατήσεις. Ελέγξτε ξανά αργότερα για ενημερώσεις.` },
  { id:52, code: `EL`, value: `Ημερομηνία έναρξης ισχύος` },
  { id:53, code: `EL`, value: `Κλειστό` },
  { id:54, code: `EL`, value: `Ανοίγει στις` },
  { id:55, code: `EL`, value: `επισκέπτες` },
  { id:56, code: `EL`, value: `Ψήφοι` },
  { id:57, code: `EL`, value: `Ημερολόγιο` },
  { id:58, code: `EL`, value: `Αγαπημένα` },
  { id:59, code: `EL`, value: `Ρυθμίσεις` },
  { id:60, code: `EL`, value: `Ρυθμίσεις λογαριασμού` },
  { id:61, code: `EL`, value: `Ονοματεπώνυμο` },
  { id:62, code: `EL`, value: `Κατάσταση συνδρομής` },
  { id:63, code: `EL`, value: `Διαχειριστείτε τη συνδρομή σας` },
  { id:64, code: `EL`, value: `Συναρπαστικά πράγματα συμβαίνουν στα παρασκήνια! Αυτή η περιοχή είναι προσωρινά μη διαθέσιμη καθώς εργαζόμαστε σκληρά για να σας προσφέρουμε νέες λειτουργίες. Μείνετε συντονισμένοι!` },
  { id:65, code: `EL`, value: `Καλώς ήρθατε στο Reserwave! Αυτοί οι όροι και οι προϋποθέσεις ("Όροι") αποτελούν μια νομικά δεσμευτική συμφωνία μεταξύ εσάς και της Reserwave. Διαβάστε προσεκτικά αυτούς τους Όρους πριν χρησιμοποιήσετε την πλατφόρμα μας. Με την πρόσβαση ή τη χρήση του Reserwave, συμφωνείτε να συμμορφώνεστε και να δεσμεύεστε από αυτούς τους Όρους. Εάν δεν συμφωνείτε με οποιοδήποτε μέρος αυτών των Όρων, παρακαλούμε να αποφύγετε τη χρήση της πλατφόρμας μας.` },
  { id:66, code: `EL`, value: `Χρησιμοποιώντας το Reserwave, συμφωνείτε με αυτούς τους Όρους και τυχόν ενημερώσεις ή τροποποιήσεις που ενδέχεται να προκύψουν. Η συνέχιση της χρήσης της πλατφόρμας μετά από τέτοιες τροποποιήσεις συνιστά αποδοχή των αναθεωρημένων Όρων.` },
  { id:67, code: `EL`, value: `Περιγραφή Υπηρεσιών` },
  { id:68, code: `EL`, value: `Το Reserwave παρέχει μια ολοκληρωμένη πλατφόρμα για τους χρήστες να ανακαλύψουν και να κάνουν κρατήσεις σε κοντινά καταστήματα σε διάφορες θέσεις. Στόχος μας είναι να βελτιώσουμε την εμπειρία σας συνδέοντάς σας με ένα ευρύ φάσμα επιχειρήσεων, διευκολύνοντάς σας την εξερεύνηση και την προστασία των τοπικών εγκαταστάσεων.` },
  { id:69, code: `EL`, value: `Απόρρητο δεδομένων χρήστη` },
  { id:70, code: `EL`, value: `Στη Reserwave, λαμβάνουμε σοβαρά υπόψη το απόρρητο και την ασφάλεια των δεδομένων σας. Οποιεσδήποτε πληροφορίες συλλέγονται από τους χρήστες αποθηκεύονται με ασφάλεια και δεν δημοσιοποιούνται ούτε πωλούνται σε τρίτους. Ανατρέξτε στο δικό μας` },
  { id:71, code: `EL`, value: `Πολιτική Απορρήτου` },
  { id:72, code: `EL`, value: `για μια λεπτομερή επισκόπηση του τρόπου με τον οποίο συλλέγουμε, χρησιμοποιούμε και προστατεύουμε τα δεδομένα σας.` },
  { id:73, code: `EL`, value: `Εμπιστευτικότητα πληροφοριών καταστήματος` },
  { id:74, code: `EL`, value: `Θέλουμε να διαβεβαιώσουμε τα συνεργαζόμενα καταστήματα ότι δίνουμε βαρύτητα στην εμπιστευτικότητα των πληροφοριών τους. Το Reserwave δεν αποκαλύπτει λεπτομέρειες σχετικά με τα έσοδα του καταστήματος, τα στατιστικά στοιχεία των κρατήσεων ή άλλα ιδιόκτητα δεδομένα που ανήκουν στα καταστήματα της πλατφόρμας μας.` },
  { id:75, code: `EL`, value: `Καταλληλότητα χρήστη` },
  { id:76, code: `EL`, value: `Πρέπει να πληροίτε τα κριτήρια για να χρησιμοποιήσετε το Reservwave. Χρησιμοποιώντας την πλατφόρμα μας, επιβεβαιώνετε ότι πληροίτε οποιαδήποτε ηλικία ή άλλες προϋποθέσεις καταλληλότητας.` },
  { id:77, code: `EL`, value: `Συμπεριφορά χρήστη` },
  { id:78, code: `EL`, value: `Οι χρήστες πρέπει να τηρούν αποδεκτή συμπεριφορά στο Reservwave. Οποιαδήποτε κακή χρήση ή παραβίαση αυτών των όρων μπορεί να οδηγήσει στον τερματισμό του λογαριασμού σας. Ενθαρρύνουμε μια κοινότητα με σεβασμό και θετική για όλους τους χρήστες.` },
  { id:79, code: `EL`, value: `Τερματισμός Λογαριασμών` },
  { id:80, code: `EL`, value: `Διατηρούμε το δικαίωμα να τερματίσουμε τους λογαριασμούς χρηστών ή τις υπηρεσίες υπό συνθήκες που κρίνονται κατάλληλες από την Reserwave. Αυτό περιλαμβάνει περιπτώσεις μη συμμόρφωσης με αυτούς τους Όρους ή οποιαδήποτε ακατάλληλη συμπεριφορά στην πλατφόρμα.` },
  { id:81, code: `EL`, value: `Τον περιορισμό της ευθύνης` },
  { id:82, code: `EL`, value: `Η Reserwave δεν ευθύνεται για τυχόν ζημιές που υποστούν οι χρήστες ή τα καταστήματα. Οι χρήστες και τα καταστήματα χρησιμοποιούν την πλατφόρμα μας με δική τους ευθύνη. Προσπαθούμε να παρέχουμε μια αξιόπιστη και ασφαλή πλατφόρμα, αλλά δεν μπορούμε να εγγυηθούμε αδιάλειπτη, χωρίς σφάλματα ή ασφαλή πρόσβαση στις υπηρεσίες μας.` },
  { id:83, code: `EL`, value: `Αλλαγές στους Όρους` },
  { id:84, code: `EL`, value: `Ενδέχεται να ενημερώσουμε ή να τροποποιήσουμε αυτούς τους Όρους και οι χρήστες θα ενημερώνονται για τέτοιες αλλαγές μέσω ειδοποιήσεων στην πλατφόρμα ή μέσω email. Η συνεχής χρήση του Reserwave συνιστά αποδοχή των ενημερωμένων Όρων.` },
  { id:85, code: `EL`, value: `Στοιχεία επικοινωνίας` },
  { id:86, code: `EL`, value: `Για ερωτήσεις ή απορίες, επικοινωνήστε μαζί μας στο` },
  { id:87, code: `EL`, value: `Εκτιμούμε τα σχόλιά σας και είμαστε εδώ για να σας βοηθήσουμε.` },
  { id:88, code: `EL`, value: `Ολόκληρη η συμφωνία` },
  { id:89, code: `EL`, value: `Αυτοί οι Όροι αποτελούν τη συνολική συμφωνία μεταξύ των χρηστών και της Reservwave, αντικαθιστώντας τυχόν προηγούμενες συμφωνίες, συζητήσεις ή συνεννοήσεις.` },
  { id:90, code: `EL`, value: `Διαχωρισιμότητα` },
  { id:91, code: `EL`, value: `Εάν οποιοδήποτε μέρος αυτών των Όρων κριθεί μη εκτελεστό, οι υπόλοιποι Όροι θα παραμείνουν σε ισχύ.` },
  { id:92, code: `EL`, value: `Πληροφορίες που Συλλέγουμε` },
  { id:93, code: `EL`, value: `Πληροφορίες που παρέχονται από τον χρήστη` },
  { id:94, code: `EL`, value: `Ενδέχεται να συλλέξουμε προσωπικές πληροφορίες που παρέχετε οικειοθελώς όταν χρησιμοποιείτε το Reserwave. Αυτό μπορεί να περιλαμβάνει, αλλά δεν περιορίζεται σε:` },
  { id:95, code: `EL`, value: `Όνομα` },
  { id:96, code: `EL`, value: `Διεύθυνση ηλεκτρονικού ταχυδρομείου` },
  { id:97, code: `EL`, value: `Τηλεφωνικό νούμερο` },
  { id:98, code: `EL`, value: `Προτιμήσεις χρήστη` },
  { id:99, code: `EL`, value: `Πληροφορίες που συλλέγονται αυτόματα` },
  { id:100, code: `EL`, value: `Ενδέχεται επίσης να συλλέγουμε πληροφορίες αυτόματα καθώς πλοηγείστε και αλληλεπιδράτε με το Reserwave. Αυτό μπορεί να περιλαμβάνει:` },
  { id:101, code: `EL`, value: `Πληροφορίες συσκευής` },
  { id:102, code: `EL`, value: `διεύθυνση IP` },
  { id:103, code: `EL`, value: `Δεδομένα χρήσης` },
  { id:104, code: `EL`, value: `Δεδομένα τοποθεσίας` },
  { id:105, code: `EL`, value: `Πώς χρησιμοποιούμε τις πληροφορίες σας` },
  { id:106, code: `EL`, value: `Χρησιμοποιούμε τις συλλεγόμενες πληροφορίες για τους ακόλουθους σκοπούς:` },
  { id:107, code: `EL`, value: `Να παρέχουμε και να βελτιώνουμε τις υπηρεσίες μας` },
  { id:108, code: `EL`, value: `Για να εξατομικεύσετε την εμπειρία σας στο Reserwave` },
  { id:109, code: `EL`, value: `Για επικοινωνία μαζί σας, συμπεριλαμβανομένης της απάντησης σε ερωτήματα` },
  { id:110, code: `EL`, value: `Για αποστολή σχετικών ειδοποιήσεων και ενημερώσεων` },
  { id:111, code: `EL`, value: `Για να αναλύσουμε και να ενισχύσουμε την ασφάλεια της πλατφόρμας μας` },
  { id:112, code: `EL`, value: `Ασφάλεια δεδομένων` },
  { id:113, code: `EL`, value: `Λαμβάνουμε σοβαρά υπόψη την ασφάλεια των πληροφοριών σας και εφαρμόζουμε εύλογα μέτρα ασφαλείας για την προστασία τους από μη εξουσιοδοτημένη πρόσβαση, αποκάλυψη, τροποποίηση και καταστροφή.` },
  { id:114, code: `EL`, value: `Κοινή χρήση πληροφοριών` },
  { id:115, code: `EL`, value: `Δεν πουλάμε ούτε κοινοποιούμε τις προσωπικές σας πληροφορίες σε τρίτους για σκοπούς μάρκετινγκ. Ενδέχεται να μοιραστούμε τις πληροφορίες σας με τρίτους παρόχους υπηρεσιών που μας βοηθούν στη λειτουργία της πλατφόρμας μας, υπό την προϋπόθεση ότι συμφωνούν να διατηρήσουν αυτές τις πληροφορίες εμπιστευτικές.` },
  { id:116, code: `EL`, value: `Cookies και τεχνολογίες παρακολούθησης` },
  { id:117, code: `EL`, value: `Το Reserwave χρησιμοποιεί cookies και παρόμοιες τεχνολογίες παρακολούθησης για να βελτιώσει την εμπειρία σας στην πλατφόρμα μας. Μπορείτε να διαχειριστείτε τις προτιμήσεις σας για τα cookie μέσω των ρυθμίσεων του προγράμματος περιήγησής σας.` },
  { id:118, code: `EL`, value: `Οι επιλογές σας` },
  { id:119, code: `EL`, value: `Έχετε το δικαίωμα να` },
  { id:120, code: `EL`, value: `Πρόσβαση, ενημέρωση ή διαγραφή των προσωπικών σας στοιχείων` },
  { id:121, code: `EL`, value: `Εξαίρεση από ορισμένες επικοινωνίες` },
  { id:122, code: `EL`, value: `Απενεργοποιήστε τα cookies μέσω των ρυθμίσεων του προγράμματος περιήγησής σας` },
  { id:123, code: `EL`, value: `Αλλαγές σε αυτήν την Πολιτική Απορρήτου` },
  { id:124, code: `EL`, value: `Ενδέχεται να ενημερώσουμε αυτήν την Πολιτική Απορρήτου για να αντικατοπτρίζει τις αλλαγές στις πρακτικές δεδομένων μας. Η ημερομηνία έναρξης ισχύος θα αναθεωρηθεί αναλόγως και σας συνιστούμε να ελέγχετε περιοδικά αυτήν τη σελίδα για τυχόν ενημερώσεις.` },
  { id:125, code: `EL`, value: `Επικοινωνήστε μαζί μας` },
  { id:126, code: `EL`, value: `Εάν έχετε οποιεσδήποτε ερωτήσεις ή προβληματισμούς σχετικά με την παρούσα Πολιτική Απορρήτου, επικοινωνήστε μαζί μας στο` },
  { id:127, code: `EL`, value: `Συνδεθείτε με πελάτες, Διαχείριση κρατήσεων` },
  { id:128, code: `EL`, value: `Καλώς ήλθατε στο Reserwave, όπου συνδέουμε τοπικές επιχειρήσεις με πελάτες όπως ποτέ άλλοτε. Ελάτε μαζί μας και αναπτύξτε την επιχείρησή σας γίνοντας συνεργάτης.` },
  { id:129, code: `EL`, value: `Βασικά πλεονεκτήματα` },
  { id:130, code: `EL`, value: `Αυξήστε την ορατότητα: Προσεγγίστε ένα ευρύτερο κοινό στην τοπική σας κοινότητα.` },
  { id:131, code: `EL`, value: `Απρόσκοπτες κρατήσεις: Διαχειριστείτε τις κρατήσεις χωρίς κόπο μέσω της φιλικής προς τον χρήστη πλατφόρμας μας.` },
  { id:132, code: `EL`, value: `Ενισχύστε τη βάση πελατών σας: Προσελκύστε νέους πελάτες που αναζητούν επιχειρήσεις σαν τη δική σας.` },
  { id:133, code: `EL`, value: `Πως δουλεύει` },
  { id:134, code: `EL`, value: `Εγγραφή: Συμπληρώστε μια απλή φόρμα με τα στοιχεία της επιχείρησής σας για να ξεκινήσετε.` },
  { id:135, code: `EL`, value: `Προσθέστε τις υπηρεσίες σας: Ενσωματώστε τις υπηρεσίες σας με την ευελιξία να δημιουργήσετε τα δικά σας πακέτα.` },
  { id:136, code: `EL`, value: `Έναρξη σύνδεσης: Μόλις εγκριθεί, αρχίστε να λαμβάνετε κρατήσεις και να αλληλεπιδράτε με νέους πελάτες.` },
  { id:137, code: `EL`, value: `Χρειάζεστε παρουσίαση;` },
  { id:138, code: `EL`, value: `Συμπληρώστε την παρακάτω φόρμα` },
  { id:139, code: `EL`, value: `Επιβεβαίβωση αιτήματος` },
  { id:140, code: `EL`, value: `Εγγραφείτε στη συνδρομή` },
  { id:141, code: `EL`, value: `Εάν θέλετε να εγγραφείτε στην πλατφόρμα μας, μπορείτε να ξεκινήσετε τη συνδρομή σας τώρα. Στη συνέχεια, η ομάδα μας θα επικοινωνήσει μαζί σας σύντομα για να υποβάλετε το κατάστημά σας στο Reserwave.` },
  { id:142, code: `EL`, value: `Επικοινωνήστε μαζί μας τώρα` },
  { id:143, code: `EL`, value: `Για οποιαδήποτε απορία ή βοήθεια, η ομάδα υποστήριξής μας είναι έτοιμη να βοηθήσει. Επικοινωνήστε μαζί μας στο` },
  { id:144, code: `EL`, value: `Σύντομα: Διαδραστικός χάρτης` },
  { id:145, code: `EL`, value: `Επιλεγμένη υπηρεσία` },
  { id:146, code: `EL`, value: `Η τοποθεσία σου` },
  { id:147, code: `EL`, value: `Ανενεργή` },
  { id:148, code: `EL`, value: `Ενεργή` },
  { id:149, code: `EL`, value: `Ανοιχτό` },
  { id:150, code: `EL`, value: `Μέχρι` },
  { id:151, code: `EL`, value: `Επιβεβαιωμένο στις` },
  { id:152, code: `EL`, value: `Συνδύασε το με` },
  { id:153, code: `EL`, value: `Μη επιβεβαιωμένο ακόμη` },
  { id:154, code: `EL`, value: `Ακυρώθηκε` },
  { id:155, code: `EL`, value: `Αποδοχή` },
  { id:156, code: `EL`, value: `στις` },
  { id:157, code: `EL`, value: `Χρήστες` },
  { id:158, code: `EL`, value: `Υπηρεσίες` },
  { id:159, code: `EL`, value: `Καταστήματα` },
  { id:160, code: `EL`, value: `Υποκατηγορίες` },
  { id:161, code: `EL`, value: `Κατηγορίες` },
  { id:162, code: `EL`, value: `Εγγραφή στην Συνδρομή` },
  { id:163, code: `EL`, value: `Αποδοχή Όρων` },
  { id:164, code: `EL`, value: `Καλώς ήρθατε στο Reserwave! Αυτή η Πολιτική Απορρήτου περιγράφει τον τρόπο με τον οποίο η Reserwave ("εμείς", "εμείς" ή "μας") συλλέγει, χρησιμοποιεί και προστατεύει τα προσωπικά σας στοιχεία όταν χρησιμοποιείτε την πλατφόρμα μας. Με την πρόσβαση ή τη χρήση του Reserwave, συμφωνείτε με τους όρους που περιγράφονται στην παρούσα Πολιτική Απορρήτου.` },
  { id:165, code: `EL`, value: `Ανοίγει` },
  { id:166, code: `EL`, value: `Δευτέρα` },
  { id:167, code: `EL`, value: `Τρίτη` },
  { id:168, code: `EL`, value: `Τετάρτη` },
  { id:169, code: `EL`, value: `Πέμπτη` },
  { id:170, code: `EL`, value: `Παρασκευή` },
  { id:171, code: `EL`, value: `Σάββατο` },
  { id:172, code: `EL`, value: `Κυριακή` },
  { id:173, code: `EL`, value: `δευτέρα` },
  { id:174, code: `EL`, value: `τρίτη` },
  { id:175, code: `EL`, value: `τετάρτη` },
  { id:176, code: `EL`, value: `πέμπτη` },
  { id:177, code: `EL`, value: `παρασκευή` },
  { id:178, code: `EL`, value: `σάββατο` },
  { id:179, code: `EL`, value: `κυριακή` },
  { id:180, code: `EL`, value: `Επιλέξτε μια υπηρεσία πριν συνεχίσετε` },
  { id:181, code: `EL`, value: `Προσθέστε μια ημερομηνία πριν συνεχίσετε` },
  { id:182, code: `EL`, value: `Επιλέξτε ώρα πριν συνεχίσετε` },
  { id:183, code: `EL`, value: `Απαιτείται σύνδεση για να συνεχίσετε` },
  { id:184, code: `EL`, value: `Επιτυχία` },
  { id:185, code: `EL`, value: `Μια άλλη κράτηση έχει ήδη προγραμματιστεί για αυτήν την ώρα σε αυτόν τον λογαριασμό` },
  { id:186, code: `EL`, value: `Ωχ! Κάτι δεν πήγε όπως είχε προγραμματιστεί` },
  { id:187, code: `EL`, value: `Παρακαλώ εισάγετε το email σας για να συνδεθείτε` },
  { id:188, code: `EL`, value: `Το email που εισάγατε δεν είναι έγκυρο` },
  { id:189, code: `EL`, value: `Για να συνεχίσετε, εισαγάγετε τον κωδικό πρόσβασής σας` },
  { id:190, code: `EL`, value: `Το email δεν μπορεί να είναι κενό` },
  { id:191, code: `EL`, value: `Εισαγάγετε το όνομά σας για να συνεχίσετε` },
  { id:192, code: `EL`, value: `Θα επικοινωνήσουμε μαζί σας σύντομα` },
  { id:193, code: `EL`, value: `Προσθέστε όνομα για να συνεχίσετε` },
  { id:194, code: `EL`, value: `Προσθέστε επώνυμο για να συνεχίσετε` },
  { id:195, code: `EL`, value: `Παρακαλώ εισάγετε το email σας` },
  { id:196, code: `EL`, value: `Εισαγάγετε τον αριθμό τηλεφώνου σας` },
  { id:197, code: `EL`, value: `Παρακαλώ εισάγετε έναν έγκυρο αριθμό τηλεφώνου` },
  { id:198, code: `EL`, value: `Εισαγάγετε έναν κωδικό πρόσβασης` },
  { id:199, code: `EL`, value: `Ο κωδικός πρόσβασης πρέπει να αποτελείται από τουλάχιστον 8 χαρακτήρες` },
  { id:200, code: `EL`, value: `Καλως ήρθατε! Είστε πλέον μέρος του Reserwave` },
  { id:201, code: `EL`, value: `Η κράτηση σας ακυρώθηκε` },
  { id:202, code: `EL`, value: `Επιτυχής αποσύνδεση` },
  { id:203, code: `EN`, value: `Double-check your decision` },
  { id:204, code: `EN`, value: `This reservation will be permanently removed and cannot be restored` },
  { id:203, code: `EL`, value: `Ελέγξτε ξανά την απόφασή σας` },
  { id:204, code: `EL`, value: `Αυτή η κράτηση θα καταργηθεί οριστικά και δεν θα μπορεί να αποκατασταθεί` }, 
  { id:205, code: `EN`, value: `remaining` },	
  { id:205, code: `EL`, value: `απομένουν` },
  { id:203, code: `EL`, value: `Ελέγξτε ξανά την απόφασή σας` },
  { id:204, code: `EL`, value: `Αυτή η κράτηση θα καταργηθεί οριστικά και δεν θα μπορεί να αποκατασταθεί` },
  { id:205, code: `EL`, value: `απομένουν` },
  { id:206, code: `EL`, value: `διαθέσιμα` },
  { id:207, code: `EL`, value: `Δεν έχετε αγαπημένα καταστήματα αυτή τη στιγμή. Για ευκολότερη πρόσβαση αργότερα, συμπεριλάβετε ένα κατάστημα σε αυτήν τη λίστα.` },
  { id:208, code: `EL`, value: `Άρχισε τώρα` },
  { id:209, code: `EL`, value: `Σύνδεσμος` },
  { id:210, code: `EL`, value: `Κατηγορία` },
  { id:211, code: `EL`, value: `Περιοχή` },
  { id:212, code: `EL`, value: `Διεύθυνση` },
  { id:213, code: `EL`, value: `Πόλη` },
  { id:214, code: `EL`, value: `Ταχυδρομικός Κώδικας` },
  { id:215, code: `EL`, value: `Χώρα` },
  { id:216, code: `EL`, value: `Ταυτόχρονα` },
  { id:217, code: `EL`, value: `Σύνδεσμος εικόνας` },
  { id:218, code: `EL`, value: `Προβολή στη μηχανή αναζήτησης` },
  { id:219, code: `EL`, value: `Ρυθμίσεις καταστήματος` },
  { id:220, code: `EL`, value: `Τίτλος` },
  { id:221, code: `EL`, value: `Περιγραφή` },
  { id:222, code: `EL`, value: `Διάρκεια` },
  { id:223, code: `EL`, value: `Τιμή` },
  { id:224, code: `EL`, value: `Αρχική Τιμή` },
  { id:225, code: `EL`, value: `Ανεξάρτητο` },
  { id:226, code: `EL`, value: `Αυτόματη αποδοχή` },
  { id:227, code: `EL`, value: `Συνδυάζεται με` },
  { id:228, code: `EL`, value: `Δεν συνδυάζεται με` },
  { id:229, code: `EL`, value: `Ναι` },
  { id:230, code: `EL`, value: `Όχι` },
  { id:231, code: `EL`, value: `Προσθήκη` },
  { id:232, code: `EL`, value: `Αποθήκευση` },
  { id:233, code: `EL`, value: `Ώρες εργασίας` },
  { id:234, code: `EL`, value: `Ημέρα` },
  { id:235, code: `EL`, value: `Ώρα έναρξης` },
  { id:236, code: `EL`, value: `Ώρα λήξης` },
  { id:237, code: `EL`, value: `Πίσω στην αρχική` },
  { id:238, code: `EL`, value: `Αναζήτηση` },
  { id:239, code: `EL`, value: `Σύνδεση` },
  { id:240, code: `EL`, value: `Συνέταιρος` },
  { id:241, code: `EL`, value: `Ξέχασα τον κωδικό μου` },
  { id:242, code: `EL`, value: `Συνέχισε με την Google` },
  { id:243, code: `EL`, value: `Ανάκτηση Λογαριασμού` },
  { id:244, code: `EL`, value: `Υπό εξέταση` },
  { id:245, code: `EL`, value: `Δεν υπάρχουν` },
  { id:246, code: `EL`, value: `στο Reserwave κοντά στην περιοχή` },
  { id:247, code: `EL`, value: `ακόμα.` },
  { id:248, code: `EL`, value: `Εργαζόμαστε σκληρά για να επεκταθούμε και ελπίζουμε να έρθουμε σύντομα στην περιοχή σας.` },
  { id:249, code: `EL`, value: `Λυπούμαστε, αλλά φαίνεται ότι αυτό το κατάστημα δεν προσφέρει καμία υπηρεσία αυτήν τη στιγμή.` },
  { id:250, code: `EL`, value: `Για να συνεχίσετε με την κράτησή σας, δημιουργήστε έναν δωρεάν λογαριασμό.` },
];


